'''
Created on 2010-06-04

@author:  Mathieu Gagnon
@contact: mathieu.gagnon.10@ulaval.ca
@organization: Universite Laval

@license

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
'''

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Outcome.ui'
#
# Created: Fri Jun  4 14:39:08 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from model.OutcomeModel import OutcomeVarModel

class Ui_Outcome(object):
    '''
    This class is an automatically generated python file using the pyuic4 program and .ui file generated by Qt_Designer
    This class is the mainWindow's tab containing the outcome information of the simulation
    '''
    def __init__(self, parent):
        '''
        @summary Constructor
        @param parent: application's mainWindow
        '''
        self.parent = parent
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        #Creating grid Layouts
        self.verticalLayoutTLC = QtGui.QVBoxLayout()
        self.verticalLayoutTRC = QtGui.QVBoxLayout()
        self.verticalLayoutBLC = QtGui.QVBoxLayout()
        self.gridLayout = QtGui.QGridLayout()
        #Creating main layout
        self.mainLayout = QtGui.QVBoxLayout()
        
        #Adding Layouts to the main Layout
        self.mainLayout.addLayout(self.gridLayout)
        
        #Adding layout to the grids
        self.gridLayout.addLayout(self.verticalLayoutTLC, 0, 0)
        self.gridLayout.addLayout(self.verticalLayoutTRC, 0, 1)
        self.gridLayout.addLayout(self.verticalLayoutBLC, 1, 0)
        
        #Populating the layouts
        self.label = QtGui.QLabel()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        #Profile listView
        self.listView = QtGui.QListView()
        self.listView.setSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        self.listView.setObjectName("listView")
        #Adding items to the layout
        self.verticalLayoutTLC.addWidget(self.label)
        self.verticalLayoutTLC.addWidget(self.listView)
        self.label_2 = QtGui.QLabel()
        self.label_2.setFont(font)
        self.label_2.setObjectName("label")
        
        #Population Outcome listView
        self.listView_2 = QtGui.QListView()
        self.listView_2.setSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        self.listView_2.setObjectName("listView_2")
        #Adding items to the layout
        self.verticalLayoutTRC.addWidget(self.label_2)
        self.verticalLayoutTRC.addWidget(self.listView_2)
        self.label_3 = QtGui.QLabel()
        self.label_3.setFont(font)
        self.label_3.setObjectName("label")
        
        #Environment Outcome listView
        self.listView_3 = QtGui.QListView()
        self.listView_3.setSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        self.listView_3.setObjectName("listView_2")
        #Adding items to the layout
        self.verticalLayoutBLC.addWidget(self.label_3)
        #self.verticalLayoutBLC.addSpacing(20)
        self.verticalLayoutBLC.addWidget(self.listView_3)        
        
        #Setting main Layout
        Form.setLayout(self.mainLayout)
        self.mainLayout.setMargin(50)
        self.gridLayout.setSpacing(30)
        self.verticalLayoutTLC.setSpacing(5)
        self.verticalLayoutBLC.setSpacing(5)
        self.verticalLayoutTRC.setSpacing(5)
        
        self.connect(self.listView, QtCore.SIGNAL("clicked(const QModelIndex)"),self.updateView)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Available profiles :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Available variables :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Environment :", None, QtGui.QApplication.UnicodeUTF8))

        
    def updateView(self,index):
        '''
        @summary Updates Population Outcome list when a different profile is selected
        '''
        if index.isValid():
            self.listView_2.setModel(OutcomeVarModel(self.listView.model().baseModel,self.parent.getOutputNode(),self.listView.model().getVarNameFromIndex(index),self,self.parent))
    